name: 'Tag SemVer'
description: 'Automatically create a tag using semver when a pull request is merged into a base branch.'
inputs: {}
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACTIONS_TOKEN: ${{ inputs.token }}