name: 'Tag SemVer'
description: 'Automatically create a tag using semver when a pull request is merged into a base branch.'
outputs: {}
inputs:
  token:
    required: true
    description: GitHub token
    
runs:
  using: docker
  image: Dockerfile
  env:
    GH_TOKEN: ${{ inputs.token }}