name: Tag on Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Set up authentication
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}

    - name: Run Docker Action to Calculate Tag
      id: calculate_tag
      uses: ./
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

    - name: Create and Push Tag
      run: |
        git tag ${{ steps.calculate_tag.outputs.new_tag }}
        git push origin ${{ steps.calculate_tag.outputs.new_tag }}
